<?php 
    include_once('inc/theme_support.php');
    include_once('inc/wp_enqueue_scripts.php');
    include_once('inc/widgets_init.php');
    include_once('inc/custom_post.php');
    include_once('inc/extra_functions.php');
    include_once('inc/cmb2_custome_fields.php');
    require_once('inc/redux-framework-master/redux-framework.php');
    require_once('inc/redux_auservice_config.php');
    require_once('inc/plugin_auto_activation.php');
